[package]

name = "static"
version = "0.1.0"
authors = ["Zach Pomerantz <zmp@umich.edu>"]

[lib]

name = "static"
path = "src/lib.rs"

[dependencies]
iron = "*"
mount = "*"
time = "*"
router = "*"
iron-test = "*"
